# Generated by Django 5.1.7 on 2025-03-27 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('headphone', 'Headphone'), ('smartwatch', 'Smartwatch'), ('speaker', 'Speaker'), ('accessories', 'Accessories'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.seller')),
                ('tags', models.ManyToManyField(blank=True, related_name='related_to', to='services.product')),
            ],
        ),
    ]
